services:
  transactions-dedup:
    image: ghcr.io/qubic/transactions-dedup:${DEDUP_VERSION}
#    image: sha256:651490bb4768bc9fa283b5fa15902512e015a16e1a1d9c40d697d2ade4ee9c26
    container_name: transactions-dedup
    user: 1000:1000
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=localhost:9092
      - STREAMS_STATE_DIR=/var/kafka-streams
      - DEDUP_INPUT_TOPIC=qubic-transactions-incoming-local
      - DEDUP_OUTPUT_TOPIC=qubic-transactions-local
      - DEDUP_RETENTION_DURATION=1d
    network_mode: host
    volumes:
      - ./data:/var/kafka-streams
    restart: no
