services:
  event-logs-dedup:
#    image: ghcr.io/qubic/tick-transactions-dedup:${DEDUP_VERSION}
    image: sha256:16b77c6380f2ab4f66d31dabd2b754def3536a1e7709e73dfc9a0d102e4bb81e
    container_name: tick-transactions-dedup
    user: 1000:1000
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=localhost:9092
      - STREAMS_STATE_DIR=/var/kafka-streams
      - DEDUP_INPUT_TOPIC=qubic-transactions-incoming-local
      - DEDUP_OUTPUT_TOPIC=qubic-transactions-local
      - DEDUP_RETENTION_DURATION=1d
    network_mode: host
    volumes:
      - ./data:/var/kafka-streams
    restart: no
