services:
  event-logs-dedup:
#    image: ghcr.io/qubic/tick-data-dedup:${DEDUP_VERSION}
    image: sha256:5830ee2532d0700e9d49ea8f41e783ec78bc3aafcb5f6d43e9cdc43540c402fa
    container_name: tick-data-dedup
    user: 1000:1000
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=localhost:9092
      - STREAMS_STATE_DIR=/var/kafka-streams
      - DEDUP_INPUT_TOPIC=qubic-tick-data-incoming-local
      - DEDUP_OUTPUT_TOPIC=qubic-tick-data-local
      - DEDUP_RETENTION_DURATION=1d
    network_mode: host
    volumes:
      - ./data:/var/kafka-streams
    restart: no
